project_id = "vjifxhyypuporrbqgibt"

[functions.parsebot-proxy]
verify_jwt = false

[functions.firecrawl-ad-details]
verify_jwt = false

[functions.sync-ads]
verify_jwt = false

[functions.admin-sources]
verify_jwt = false

[functions.scrape-musikborsen]
verify_jwt = false
